{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "graphsql.secretName" . }}
  labels:
    {{- include "graphsql.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.database.url }}
  database-url: {{ .Values.database.url | b64enc | quote }}
  {{- else if .Values.database.host }}
  database-url: {{ include "graphsql.databaseUrl" . | b64enc | quote }}
  {{- end }}
  {{- if .Values.database.password }}
  database-password: {{ .Values.database.password | b64enc | quote }}
  {{- end }}
  {{- if .Values.apiKey }}
  api-key: {{ .Values.apiKey | b64enc | quote }}
  {{- end }}
{{- end }}
